apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: glasswing-agent-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: glasswing-agent-operator
subjects:
- kind: ServiceAccount
  name: glasswing-agent-operator
  namespace: glasswing-agent-operator
